### ISSUE TITLE
Best testing practices

### ISSUE THREAD

**Issue by 8bitgentleman** [joaomgcd/AutoToolsWebScreens#3]
What's the best way, on a device, to test web screen presets with multiple files? Do you put multiple links in the source?

**Comment by joaomgcd** [comment]
Presets have to be based on publicly accessible files so keep that in mind.
You can host them on Dropbox for example, and use their share URLs.

- Put other files in the same folder as the main source file
- Reference those files in the main file using just the file name, like **<script src="myscripts.js"></script>** for example
- When creating the preset add those files in the **Files** field with the format **https://www.dropbox.com/s/caaapa4yy0/myscripts.js?dl=1|myscripts.js** which is the full URL followed "|" and then followed by the file name

Now when you refresh your preset on your device the myscripts.js file will always be downloaded into the same folder as the main source file.

Let me know if you have any trouble!

**Comment by 8bitgentleman** [comment]
I've got an additional question about this. I use the live coding website [codepen.com](www.codepen.com) to put together a webscenes and such. Codepen allows you to directly link to the html/css/js of your project. The URLs look something like this:
[https://codepen.io/thearchitect21/pen/rwgWKo.html](https://codepen.io/thearchitect21/pen/rwgWKo.html)
[https://codepen.io/thearchitect21/pen/rwgWKo.css](https://codepen.io/thearchitect21/pen/rwgWKo.css)
[https://codepen.io/thearchitect21/pen/rwgWKo.js](https://codepen.io/thearchitect21/pen/rwgWKo.js)

When testing a web preset how would I link all of those files in the source?
It seems I should put this under source 

[https://codepen.io/thearchitect21/pen/rwgWKo.html](https://codepen.io/thearchitect21/pen/rwgWKo.html)|rwgWKo.html|[https://codepen.io/thearchitect21/pen/rwgWKo.css](https://codepen.io/thearchitect21/pen/rwgWKo.css)|rwgWKo.css|[https://codepen.io/thearchitect21/pen/rwgWKo.js](https://codepen.io/thearchitect21/pen/rwgWKo.js)|rwgWKo.js

but that doesn't work and causes Autotools to crash.

Is this possible or am I off base?

**Comment by joaomgcd** [comment]
It should probably be something like:

https://codepen.io/thearchitect21/pen/rwgWKo.html|rwgWKo.html
https://codepen.io/thearchitect21/pen/rwgWKo.css|rwgWKo.css
https://codepen.io/thearchitect21/pen/rwgWKo.js|rwgWKo.js

Can you give that a try? :)

**Comment by 8bitgentleman** [comment]
Pasting that into the source input field just crashed autotools as soon as I hit OK on the source dialog :/

**Comment by joaomgcd** [comment]
Oh, that's not supposed to go into the source field, sorry. It's supposed to go into the Files list in the main AutoTools app -> Manage Web Screens -> Files

Let me know if this helps

**Comment by 8bitgentleman** [comment]
Hmm I don't see Files under Manage Web Screens in the main Autotools App 
![screenshot_20170718-084717](https://user-images.githubusercontent.com/4028391/28317637-cd6c7fc0-6b95-11e7-94b7-91a35c3fa5a0.png)

**Comment by joaomgcd** [comment]
You have to select the "Material Design Card" screen for example (which is the one you created) and it'll show up as an option :)

But if you want to create a new one use the "Save" option in the Tasker Web Screen configuration screen and you will be able to set the files there as well.

**Comment by 8bitgentleman** [comment]
Great! I've got it all sorted now :)

**Comment by joaomgcd** [comment]
Awesome! :) Glad to hear!!
